spring.application.name=bookservice

spring.cloud.config.retry.max-attempts=15
spring.cloud.config.retry.initial-interval=5000
spring.cloud.config.retry.multiplier=1.5
spring.cloud.config.retry.max-interval=50000

eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.fail-fast=true
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=CONFIGSERVER
spring.config.import=optional:configserver:
# spring.config.import=optional:configserver:http://configserver:8888
# spring.cloud.config.uri=http://configserver:8888
spring.cloud.config.name=bookservice
